name: Deploy PdfEdit

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 91.98.121.223
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/pdfedit
            git reset --hard
            git pull
            sudo systemctl restart pdfedit
          known_hosts: |
            91.98.121.223 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGZiCY+A5o+OXvBLqmVq0dTnivb/r+7sYlz5Ess/kQMy
