name: Deploy PdfEdit

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Write SSH key from base64 secret
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY_B64 }}" | base64 -d > key.pem
          chmod 600 key.pem

      - name: Trust server host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        run: |
          ssh -i key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            cd /opt/pdfedit &&
            git fetch origin main &&
            git reset --hard origin/main &&
            systemctl restart pdfedit
          '
