name: Deploy sites/ to server

on:
  push:
    branches: [ main ]
    paths:
      - "sites/**"      # csak akkor fusson, ha a sites/ mappában változás van
      - ".github/workflows/deploy-sites.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Rsync sites/ → /srv/metori/sites/
        run: |
          rsync -az --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            sites/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/metori/sites/
